loja/estoque/urls.py
from django.urls import path
from . import views

app_name = "estoque"

urlpatterns = [
    path("", views.index, name="index"),
    path('hora/', views.hora, name="hora"),
    path('listagem/', views.listagem, name='listagem'),
    path("produto/", views.produtoView, name='produto'),
    path("marca/", views.marcaView, name="marca"),
    path("categoria/", views.categoriaView, name="categoria"),
]

loja/loja/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include("cliente.urls")),
    path("estoque/", include("estoque.urls")),
    # path("venda/", include("venda.urls")),
]

loja/estoque/models.py
from django.db import models

# Create your models here.

# TODO Implementar o modelo de estoque.


class Marca(models.Model):

    nomeMarca = models.CharField(verbose_name="Nome da Marca", max_length=15)

    def __str__(self):
        return self.nomeMarca


class Categoria(models.Model):

    nomeCategoria = models.CharField(
        verbose_name="Nome da Categoria", max_length=15)
    # TODO Implementar a lista de produtos relacionada a esta marca.
    produtoCategoria = None

    def __str__(self):
        return self.nomeCategoria


class Produto(models.Model):

    nomeProduto = models.CharField(verbose_name="Nome do Produto", max_length=20)
    descProduto = models.TextField(verbose_name="Descrição do Produto")
    # Existe uma função do python que retorna o valor local. Locate.
    precoProduto = models.DecimalField(verbose_name="Preço Unitario", max_digits=8, decimal_places=2)
    categoriaProduto = models.ForeignKey(Categoria, verbose_name="Categoria", on_delete=models.CASCADE)
    marcaProduto = models.ForeignKey(Marca, verbose_name="Marca", on_delete=models.PROTECT)

    def __str__(self):
        return self.nomeProduto 
    

""" class Estoque(models.Model):
    codProduto = models.ForeignKey(Produto, verbose_name="Codigo Produto", on_delete=models.CASCADE)
    dataMovimentacao = models.DateTime(verbose_name="Data da Movimentação")
    quantidade = models.IntegerField(verbose_name="Quantidade")
    tipo """

loja/estoque/forms.py
from django.forms import ModelForm
from .models import Produto
from .models import Marca
from .models import Categoria

class ProdutoForm(ModelForm):
    class Meta:
        model = Produto
        fields = "__all__"

class MarcaForm(ModelForm):
    class Meta:
        model = Marca
        fields = "__all__"

class CategoriaForm(ModelForm):
    class Meta:
        model = Categoria
        fields = "__all__"

loja/estoque/views.py
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from .forms import CategoriaForm, MarcaForm, ProdutoForm
from .models import Produto

# Create your views here.

def index(request):
    return render(request, "estoque/index.html",{})

def hora(request):
    context = {"hora":datetime.now()}
    return render(request, "estoque/hora.html", context)

"""
    Gerar Uma Lista de Todos os produtos disponiveis em cadastro
"""
def listagem(request):
    produtos = Produto.objects.all() 
    return render(request,'estoque/estoque.html',{'produtos':produtos})


def produtoView(request):
    context = {}
    form = ProdutoForm()
    context['form'] = form
    if request.method == "POST":
        resultado = procutoForm(request.POST)
        if resultado.is_valid():
            resultado.save()
            sucesso = "Salvo com Sucesso!"
            context['sucesso'] = sucesso
        else:
            erro = "Erro! Cadastro não salvo."
            context['erro'] = erro
    return render(request, "estoque/produto.html", context)

def marcaView(request):
    context = {}
    form = MarcaForm()
    context['form'] = form
    if request.method == "POST":
        resultado = MarcaForm(request.POST)
        if resultado.is_valid():
            resultado.save()
            sucesso = "Salvo com Sucesso!"
            context['sucesso'] = sucesso
        else:
            erro = "Erro! Cadastro não salvo."
            context['erro'] = erro

    return render(request, "estoque/marca.html", context)

def categoriaView(request):
    context = {}
    form = CategoriaForm()
    context['form'] = form
    if request.method == "POST":
        resultado = CategoriaForm(request.POST)
        if resultado.is_valid():
            resultado.save()
            sucesso = "Salvo com Sucesso!"
            context['sucesso'] = sucesso
        else:
            erro = "Erro! Cadastro não salvo."
            context['erro'] = erro
    return render(request, "estoque/categoria.html", context)

loja/estoque/templates/estoque/base.html
<!DOCTYPE html>
{% load static %}
{#Aqui será desemvolvida o template de menu do site. #} 
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <meta name="author" content="Sander Toledo">
<!-- Font Awesome -->
{% block cs %}
{% endblock cs %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <title>Sistema de Estoque</title>
{% block js %}
{% endblock js %}
</head>
<body>
{# Conteudo do Site abaixo #}
  
<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">

  
  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">
    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'estoque:index' %}">Home<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'estoque:listagem' %}">Lista de Produtos</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="{% url 'estoque:hora' %}">Hora</a>
        </li>
      <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Estoque</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'estoque:produto' %}">Cadastro de Produtos</a>
          <a class="dropdown-item" href="{% url 'estoque:categoria' %}">Cadastro de Categoria</a>
          <a class="dropdown-item" href="{% url 'estoque:marca' %}">Cadastro de Marca</a>
          <a class="dropdown-item" href="#">Movimentação</a>
        <!--submenu -->
            
        </div>
      </li>

    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
        {% block conteudo %}
        {% endblock %}

<!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


<!-- Footer -->
<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
</body>
</html>

loja/estoque/templates/estoque/categoria.html
{% extends 'estoque/base.html' %}
{% block conteudo %}
    {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
        {% endif %}
    <form action="{% url 'estoque:categoria' %}" method="post">
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>{% endblock conteudo %}

loja/estoque/templates/estoque/estoque.html
{% extends 'estoque/base.html' %}
{# Esta é a minha primeira pagina. E tudo o que seria exibido na home. #}
{{% block js %}

{% endblock js %}

{% block conteudo %}
  <script type="text/javascript">
  <!--
    $(document).ready(function(){
      $("#tableSearch").on("keyup", function() {
        var value = $(this).val().toLowerCase();
        $("#myTable tr").filter(function() {
          $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
        });
      });
    });
  -->
  </script>
    <div class="table-responsive table-hover text-nowrap">
        <input class="form-control mb-4" id="tableSearch" type="text" placeholder="Pesquisar">
      <table id="dt-vertical-scroll" class="table table-sm" cellspacing="0" width="100%">
          <thead>
            <tr>
              <th scope="col">Produto</th>
              <th scope="col">Descrição</th>
              <th scope="col">Categoria</th>
              <th scope="col">Marca</th>
              <th scope="col">Preço</th>
            </tr>
          </thead>
        {% for Produto in produtos %}
          <tbody id="myTable">
            <tr scope="row">
              <td>{{Produto.nomeProduto}}</td>
              <td>{{Produto.descProduto}}</td>
              <td>{{Produto.categoriaProduto}}</td>
              <td>{{Produto.marcaProduto}}</td>
              <td>R$ {{Produto.precoProduto}}</td>
            </tr>
          </tbody>
        {% endfor %}
        </table>
    </div>
{% endblock %}

loja/estoque/templates/estoque/hora.html
{% extends 'estoque/base.html' %}
{% block conteudo %}
<h1> {{ hora }} </h1>
{% endblock conteudo %}
        

loja/estoque/templates/estoque/index.html
{% extends 'estoque/base.html' %}
{# Esta é a minha primeira pagina. E tudo o que seria exibido na home. #}
{% block conteudo %}
    <h2>Bem vindo a Loja</h2>
    <p class="text-justify">{% lorem 2 b %}</p> 
{% endblock %}

loja/estoque/templates/estoque/marca.html
{% extends 'estoque/base.html' %}
{% block conteudo %}
    {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
        {% endif %}
    <form action="{% url 'estoque:marca' %}" method="post">
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>{% endblock conteudo %}

loja/estoque/templates/estoque/produto.html
{% extends 'estoque/base.html' %}
{% block conteudo %}
    {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
        {% endif %}
    <form action="{% url 'estoque:produto' %}" method="post">
        {{form.as_p}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>
{% endblock conteudo %}

{#  #}
{% comment 'Resultado do envio do produto' %}
Forbidden (CSRF cookie not set.): /estoque/produto/
[29/Apr/2020 15:34:12] "POST /estoque/produto/ HTTP/1.1" 403 2931
{% endcomment %}