loja/cliente/urls.py
from django.urls import path
from . import views

app_name = "cliente"

urlpatterns = [
    path("", views.index, name="index"),
    path('hora/', views.hora, name="hora"),
    path('listagem/', views.listagem, name="listagem"), 
    path('cidade/', views.cidadeView, name="cidade"),
    path("endereco/", views.enderecoView, name="endereco"),
    path("cliente/", views.clienteView, name="cliente"),
    path("relatorio/", views.RelatorioAnivCliente, name="relatorio"), 
]

loja/loja/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('cliente/', include("cliente.urls")),
    path("estoque/", include("estoque.urls")),
    # path("venda/", include("venda.urls")),
]

loja/cliente/models.py
from django.db import models

"""Subclasse de Endereço"""

class Cidade(models.Model):
    nomeCidade = models.CharField(verbose_name="Cidade", max_length=15)
    nomeUF = models.CharField(verbose_name="Estado", max_length=2)

    def __str__(self):
        return self.nomeCidade+" - " + self.nomeUF

"""Modelo de Entedeço"""

class Endereco(models.Model):
    logradouroEndereco = models.CharField(
        verbose_name="Endereço do Cliente", max_length=40)
    nroEndereco = models.IntegerField(verbose_name="Número do Cliente", null=True, blank=True)
    nomeBairro = models.CharField(verbose_name="Bairro", max_length=45)
    # TODO Transformar essa relação many to many.
    cidadeEndereco = models.ForeignKey(Cidade, verbose_name="Cidade", on_delete=models.PROTECT)
    
    def __str__(self):
        return self.logradouroEndereco

"""Construção do Modelo do Cliente."""

class Cliente(models.Model):
    nomeCliente = models.CharField(
        verbose_name="Nome do Cliente", max_length=45)
    numeroCpf = models.CharField(verbose_name="Número do CPF", max_length=14)
    dataNascimento = models.DateField(verbose_name="Data de Nascimento")
    idade = models.IntegerField(verbose_name="Idade")
    # TODO Transformar essa relação many to many.
    codigoEndereco = models.ForeignKey(
        Endereco, verbose_name=("Endereço"), on_delete=models.CASCADE)

    def __str__(self):
        return self.nomeCliente
    

loja/cliente/forms.py
from django import forms
from django.forms import ModelForm

from .models import Cidade, Cliente, Endereco


class CidadeForm(ModelForm):
    class Meta:
        model = Cidade
        fields = ['nomeCidade', 'nomeUF']
        help_texts = {
            "nomeCidade":"Nome de Cidade",
            "nomeUF":"Unidade Federativa ou Estado"
        }
        labels = {
            "nomeCidade":"Cidade",
            "nomeUF":"UF"
        }
        error_messages={
        "nomeCidade":{"max_length" : "nao pode ser superior a 15 caracteres,"}
        }

class EnderecoForm(ModelForm):
    class Meta:
        model = Endereco
        fields = ['logradouroEndereco','nroEndereco', 'nomeBairro', 'cidadeEndereco' ]
        help_texts={
            'logradouroEndereco':'Favor informar o nome da Rua.',
            'nroEndereco':'Digitar o numero da casa ou apartamento.',
            'nomeBairro':'Informar o bairro.'
        }
        labels = {
            'logradouroEndereco':'Logradouro', 
            'nroEndereco':'Número',
            'nomeBairro':'Bairro',
            'cidadeEndereco':'Cidade',
        }
class ClienteForm(ModelForm):
    class Meta:
        model = Cliente
        fields = ['nomeCliente', 'numeroCpf', 'dataNascimento', 'codigoEndereco']
        
class BuscaClienteForm(forms.Form):
    nomeCliente = forms.CharField( max_length=45)
    dataNascimento = forms.CharField(max_length=10)

loja/cliente/views.py
# Create your views here.
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render

from .relatorio import Relatorio
from .forms import BuscaClienteForm, CidadeForm, ClienteForm, EnderecoForm
from .models import Cliente


def index(request):
    return render(request, "cliente/index.html", {})


def hora(request):
    context = {"hora": datetime.now()}

    return render(request, "cliente/hora.html", context)


def cidadeView(request):
    context = {}
    form = CidadeForm()
    context['form'] = form
    if request.method == "POST":
        resultado = CidadeForm(request.POST)
        if resultado.is_valid():
            resultado.save()
            sucesso = "Salvo com Sucesso!"
            context['sucesso'] = sucesso
        else:
            erro = "Erro! Cadastro não salvo."
            context['erro'] = erro
    return render(request, "cliente/cidade.html", context)


def enderecoView(request):
    context = {}
    form = EnderecoForm()
    context['form'] = form
    if request.method == "POST":
            resultado = EnderecoForm(request.POST)
            if resultado.is_valid():
                resultado.save()
                sucesso = "Endereço Salvo com Sucesso"
                context["sucesso"] = sucesso
            else:
                erro = "Endereço não foi salvo"
                context["erro"] = erro
    return render(request, "cliente/endereco.html", context)

# Cadastro de Clientes


def clienteView(request):
    context = {}
    form = ClienteForm()
    context['form'] = form
    if request.method == "POST":
        resultado = ClienteForm(request.POST)
        if resultado.is_valid():
            resultado.save()
            sucesso = "Cliente Salvo com Sucesso"
            context["sucesso"] = sucesso
        else:
            erro = "Cliente nao foi salvo"
            context["erro"] = erro
    return render(request, "cliente/cliente.html", context)


def listagem(request):
    clientes = []
    #Pesquisar Queryset
    form = BuscaClienteForm()
    if request.method == "POST":
        resultado = BuscaClienteForm(request.POST)
        if resultado.is_valid():
            nome = resultado.cleaned_data["nomeCliente"]
            dataNascimento = resultado.cleaned_data["dataNascimento"]
            clientes = Cliente.objects.filter(nomeCliente=nome)
        else:
            pass
    else:
        clientes = Cliente.objects.all()
    
    contexto = {'clientes': clientes, "form":form}
    return render(request, "cliente/listagem.html", contexto )


def RelatorioAnivCliente(request):
    
    resultado = Relatorio.relatAniversarioCliente()
    #Cliente.objects.raw(RelatorioAnivCliente)
    contexto = {"resultado":resultado}

    return render(request,'cliente/relatorio.html',contexto)

loja/cliente/templates/cliente/base.html
<!DOCTYPE html>
{% load static %}
<html lang='pt_br'>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="author" content="Sander Toledo">


<!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
  <!-- Bootstrap tooltips -->
  
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

{# CSS do HTML #}
<!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css'%}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">

{% block css %}
{% endblock css %}

<title>Meu site</title>
</head>
<body>

<!--Navbar-->
<nav class="navbar navbar-expand-lg navbar-dark primary-color">

  
  <!-- Collapse button -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
    aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <!-- Collapsible content -->
  <div class="collapse navbar-collapse" id="basicExampleNav">

    <!-- Links -->
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cliente:index' %}">Home
          <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cliente:listagem' %}">Lista de Clientes</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cliente:relatorio' %}">Relatorio de Aniversário</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href={% url 'cliente:hora' %}>Hora</a>
        </li>
      <!-- Dropdown -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">Cadastrar</a>
        <div class="dropdown-menu dropdown-primary" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'cliente:cidade' %}">Cidade</a>
          <a class="dropdown-item" href="{% url 'cliente:endereco' %}">Endereço</a>
          <a class="dropdown-item" href="{% url 'cliente:cliente' %}">Cliente</a>
        
        </div>
      </li>

    </ul>
    <!-- Links -->

    <form class="form-inline">
      <div class="md-form my-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      </div>
    </form>
  </div>
  <!-- Collapsible content -->

</nav>
        {% block conteudo %}
        {% endblock %}

<!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">Footer Content</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Links</h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!">Link 1</a>
          </li>
          <li>
            <a href="#!">Link 2</a>
          </li>
          <li>
            <a href="#!">Link 3</a>
          </li>
          <li>
            <a href="#!">Link 4</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://mdbootstrap.com/"> MDBootstrap.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</body>
</html>

loja/cliente/templates/cliente/cidade.html
{% extends 'cliente/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
        {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
        {% endif %}
    <form action="{% url 'cliente:cidade' %}" method="post">
    {% csrf_token %}
        {{form | crispy}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>
{% endblock conteudo %}

loja/cliente/templates/cliente/cliente.html
{% extends 'cliente/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
        {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
		{% endif %}

    <form action="{% url 'cliente:cliente' %}" method="post">
        {% csrf_token %}
        {{form | crispy}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>
{% endblock conteudo %}

loja/cliente/templates/cliente/endereco.html
{% extends 'cliente/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
        {% if erro %}
			<div class="alert alert-danger">{{ erro }}</div>
		{% endif %}
		{% if sucesso %}
			<div class="alert alert-success">{{ sucesso }}</div>
        {% endif %}
    <form action="{% url 'cliente:endereco' %}" method="post">
    {% csrf_token %}
        {{form | crispy}}
        <input type="submit" class="btn btn-primary" value="Salvar"/>
    </form>
{% endblock conteudo %}

loja/cliente/templates/cliente/hora.html
{% extends 'cliente/base.html' %}
{% block conteudo %}
<h1> {{ hora }} </h1>
{% endblock conteudo %}
        

loja/cliente/templates/cliente/index.html
{% extends 'cliente/base.html' %}
{% block conteudo %}
<h3><marquee>Este é o primeiro texto em Django.</marquee></h3>
<p class="text-justify">{% lorem 3 b random %}</p>

{% endblock  %}

loja/cliente/templates/cliente/listagem.html
{% extends 'cliente/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
    <div class="table-responsive table-hover text-nowrap">
        <form action="" method="post" class="form form-inline">
			{% csrf_token %}
			{{ form | crispy }}
			<input type="submit" value="Vai" />
		</form>

        <table id="dt-vertical-scroll" class="table table-sm" cellspacing="0" width="100%">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">Idade</th>
                    <th scope="col">Endereço</th>
                </tr>
            </thead>
        {% for Cliente in clientes %}
        <tbody id="myTable">
            <tr scope="row">
                <td>{{Cliente.nomeCliente}}</td>
                <td>{{Cliente.numeroCpf}}</td>
                <td>{{Cliente.dataNascimento}}</td>
                <td>{{Cliente.idade}}</td>
                <td>{{Cliente.codigoEndereco}}</td>
            </tr>
        </tbody>
        {% endfor %}
        </table>
    </div>
{% endblock conteudo %}

loja/cliente/templates/cliente/relatorio.html
{% extends 'cliente/base.html' %}
{% load crispy_forms_tags %}
{% block conteudo %}
    <table class="table table-sm">
    <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Aniversario</th>
                </tr>
            </thead>
    
    {%for Resultado in resultados%}
    <tr>
        <td>{{Resultado.0}}</td>
        <td>{{Resultado.1}}</td>
    </tr>
    {%endfor%}

    </table>
{% endblock conteudo %}